"""Formatting helpers for research markdown reports and Telegram digests."""

from __future__ import annotations

from collections import defaultdict
from datetime import UTC, datetime

from emergent.research.types import ScoredFinding


def _format_date(value: datetime | None) -> str:
    if value is None:
        return "unknown"
    dt = value if value.tzinfo is not None else value.replace(tzinfo=UTC)
    return dt.strftime("%Y-%m-%d")


def generate_markdown_report(
    *,
    run_id: str,
    highlights: list[ScoredFinding],
    rest: list[ScoredFinding],
    total_sources: int,
) -> str:
    """Generate markdown report with highlights and findings grouped by domain."""
    now = datetime.now(UTC)
    lines: list[str] = [f"# Research Digest -- {now:%Y-%m-%d}", "", "## Highlights", ""]

    if not highlights:
        lines.append("No highlights this run.")
        lines.append("")
    else:
        for idx, item in enumerate(highlights, start=1):
            finding = item.finding
            lines.extend(
                [
                    f"### [{idx}] {finding.title}",
                    (
                        f"- **Score:** {item.score:.2f} | **Source:** {finding.source} "
                        f"| **Published:** {_format_date(finding.published_at)}"
                    ),
                    f"- **URL:** {finding.url}",
                    f"- **Summary:** {finding.summary}",
                    f"- **Domain:** {finding.domain}",
                    "",
                ]
            )

    lines.extend(["## All Findings by Domain", ""])
    grouped: dict[str, list[ScoredFinding]] = defaultdict(list)
    for item in [*highlights, *rest]:
        grouped[item.finding.domain].append(item)

    for domain in sorted(grouped):
        findings = sorted(grouped[domain], key=lambda x: x.score, reverse=True)
        lines.append(f"### {domain} ({len(findings)} findings)")
        lines.append("| Score | Title | Source | URL |")
        lines.append("|---|---|---|---|")
        for item in findings:
            lines.append(
                f"| {item.score:.2f} | {item.finding.title} | {item.finding.source} | "
                f"[link]({item.finding.url}) |"
            )
        lines.append("")

    total_findings = len(highlights) + len(rest)
    lines.extend(
        [
            "---",
            (
                f"Run ID: {run_id} | Sources queried: {total_sources} | "
                f"Total findings: {total_findings} | Highlights: {len(highlights)}"
            ),
            f"Generated by Emergent Research Worker -- {now:%Y-%m-%d %H:%M:%S}",
        ]
    )
    return "\n".join(lines)


def generate_telegram_digest(
    *,
    highlights: list[ScoredFinding],
    rest_count: int,
    report_relpath: str,
    max_chars: int = 4096,
) -> str:
    """Generate Telegram-friendly digest, truncated to max_chars."""
    now = datetime.now(UTC)
    lines = [f"Research Digest -- {now:%b %d}", "", "TOP FINDINGS:", ""]

    if not highlights:
        lines.append("No high-signal findings this run.")
    else:
        for idx, item in enumerate(highlights[:3], start=1):
            finding = item.finding
            lines.append(f"{idx}. {finding.title} ({finding.source}, {item.score:.2f})")
            lines.append(f"   {finding.url}")
            lines.append("")

    lines.append(f"+{rest_count} more findings in {report_relpath}")
    digest = "\n".join(lines)
    if len(digest) <= max_chars:
        return digest
    return digest[: max_chars - 21] + "\n[... digest truncated]"
